project:
  type: website
  output-dir: _site

website:
  title: "Continuum Mechanics — Companion Site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: lectures/01-voigt_notation.qmd
        text: Voigt notation
      - href: lectures/02-decomposition.qmd
        text: Deviatoric/Spherical
      - href: lectures/03-yield-criteria.qmd
        text: Yield Criteria
      - href: lectures/04-elastic-constants.qmd
        text: Elastic Constants
      - href: problems/index.qmd
        text: Problems
    right:
      - icon: github
        href: https://github.com/MelanieInky/TME235_Lecture_companion

format:
  html:
    theme: cosmo
    toc: true
    css: styles.css
    include-after-body: resize_iframes.html
    code-fold: false
    mainfont: -apple-system, "Segoe UI", Helvetica, Arial, sans-serif

execute:
  freeze: auto
