project:
  type: website
  output-dir: _site

jupyter: python3

website:
  title: "TME235 Mechanics of Solids — Companion Site"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Topics"
        href: lectures/index.qmd
      - text: "Problems"
        href: problems/index.qmd
    right:
      - icon: github
        href: https://github.com/MelanieInky/TME235_Lecture_companion

format:
  html:
    theme: cosmo
    toc: true
    css: styles.css
    code-fold: true
    mainfont: -apple-system, "Segoe UI", Helvetica, Arial, sans-serif
