---
title: "Voigt notation"
---


The Voigt notation is a convenient way to write the generalized Hooke law, by writing the component of the strain and stress tensor as vectors.

### Stress tensor → Voigt vector

$$
\boldsymbol{\sigma} =
\begin{pmatrix}
\sigma_{11} & \sigma_{12} & \sigma_{13} \\
\sigma_{21} & \sigma_{22} & \sigma_{23} \\
\sigma_{31} & \sigma_{32} & \sigma_{33}
\end{pmatrix}
\quad\longrightarrow\quad
\underline{\sigma} =
\begin{pmatrix}
\sigma_{11} \\ \sigma_{22} \\ \sigma_{33} \\ \sigma_{23} \\ \sigma_{13} \\ \sigma_{12}
\end{pmatrix}
=
\begin{pmatrix}
\sigma_1 \\ \sigma_2 \\ \sigma_3 \\ \sigma_4 \\ \sigma_5 \\ \sigma_6
\end{pmatrix}
$$

### Strain tensor → Voigt vector

With ($\gamma_{ij} = 2\varepsilon_{ij}$, $i\neq j$):

$$
\boldsymbol{\varepsilon} =
\begin{pmatrix}
\varepsilon_{11} & \varepsilon_{12} & \varepsilon_{13} \\
\varepsilon_{21} & \varepsilon_{22} & \varepsilon_{23} \\
\varepsilon_{31} & \varepsilon_{32} & \varepsilon_{33}
\end{pmatrix}
\quad\longrightarrow\quad
\underline{\varepsilon} =
\begin{pmatrix}
\varepsilon_{11} \\ \varepsilon_{22} \\ \varepsilon_{33} \\ 2\varepsilon_{23} \\ 2\varepsilon_{13} \\ 2\varepsilon_{12}
\end{pmatrix}
=
\begin{pmatrix}
\varepsilon_{11} \\ \varepsilon_{22} \\ \varepsilon_{33} \\ \gamma_{23} \\ \gamma_{13} \\ \gamma_{12}
\end{pmatrix}
=
\begin{pmatrix}
\varepsilon_1 \\ \varepsilon_2 \\ \varepsilon_3 \\ \varepsilon_4 \\ \varepsilon_5 \\ \varepsilon_6
\end{pmatrix}
$$

## Generalized Hooke's law with Voigt notation

A place where the use of Voigt notation makes clear sense is when we consider linear elastic materials. For a linear elastic material, the stress tensor is given by

$$
\sigma_{ij} = C_{ijkl} \epsilon_{kl}
$$

where $C_{ijkl}$ is a fourth order tensor. In the lecture, we showed that because of major and minor symmetries, there are only $6\times 6 = 36$ independent component for $\boldsymbol{C}$, exactly enough to fit in a $6 \times 6$ matrix as $\underline{\sigma} = \underline{C} \underline{\epsilon}$

$$
\begin{pmatrix}
\sigma_{11} \\ \sigma_{22} \\ \sigma_{33} \\ \sigma_{23} \\ \sigma_{13} \\ \sigma_{12}
\end{pmatrix}
=
\begin{pmatrix}
C_{1111} & C_{1122} & C_{1133} & C_{1123} & C_{1113} & C_{1112} \\
C_{2211} & C_{2222} & C_{2233} & C_{2223} & C_{2213} & C_{2212} \\
C_{3311} & C_{3322} & C_{3333} & C_{3323} & C_{3313} & C_{3312} \\
C_{2311} & C_{2322} & C_{2333} & C_{2323} & C_{2313} & C_{2312} \\
C_{1311} & C_{1322} & C_{1333} & C_{1323} & C_{1313} & C_{1312} \\
C_{1211} & C_{1222} & C_{1233} & C_{1223} & C_{1213} & C_{1212}
\end{pmatrix}
\begin{pmatrix}
\epsilon_{11} \\ \epsilon_{22} \\ \epsilon_{33} \\ 2\epsilon_{23} \\ 2\epsilon_{13} \\ 2\epsilon_{12}
\end{pmatrix}
$$ {#eq-stiffness-tensor}

In this course we will mostly consider isotropic materials, in which case the stiffness matrix only has two independent components.

$$
\begin{pmatrix}
\sigma_{11} \\ \sigma_{22} \\ \sigma_{33} \\ \sigma_{23} \\ \sigma_{13} \\ \sigma_{12}
\end{pmatrix}
=
\begin{pmatrix}
2\mu+\lambda & \lambda & \lambda & 0 & 0 & 0 \\
\lambda & 2\mu+\lambda & \lambda & 0 & 0 & 0 \\
\lambda & \lambda & 2\mu+\lambda & 0 & 0 & 0 \\
0 & 0 & 0 & \mu & 0 & 0 \\
0 & 0 & 0 & 0 & \mu & 0 \\
0 & 0 & 0 & 0 & 0 & \mu
\end{pmatrix}
\begin{pmatrix}
\epsilon_{11} \\ \epsilon_{22} \\ \epsilon_{33} \\ 2\epsilon_{23} \\ 2\epsilon_{13} \\ 2\epsilon_{12}
\end{pmatrix}
$$ {#eq-voigt-stiffness}

$$
\begin{pmatrix}
\epsilon_{11} \\ \epsilon_{22} \\ \epsilon_{33} \\ 2\epsilon_{23} \\ 2\epsilon_{13} \\ 2\epsilon_{12}
\end{pmatrix}
=
\frac{1}{E}
\begin{pmatrix}
1 & -\nu & -\nu & 0 & 0 & 0 \\
-\nu & 1 & -\nu & 0 & 0 & 0 \\
-\nu & -\nu & 1 & 0 & 0 & 0 \\
0 & 0 & 0 & 2(1+\nu) & 0 & 0 \\
0 & 0 & 0 & 0 & 2(1+\nu) & 0 \\
0 & 0 & 0 & 0 & 0 & 2(1+\nu)
\end{pmatrix}
\begin{pmatrix}
\sigma_{11} \\ \sigma_{22} \\ \sigma_{33} \\ \sigma_{23} \\ \sigma_{13} \\ \sigma_{12}
\end{pmatrix}.
$$ {#eq-voigt-compliance}