---
title: "Deviatoric / Spherical Decomposition"
---

## Deviatoric and Volumetric decomposition of a tensor

Consider either the stress or the strain tensor. They can be decomposed into its spherical and volumetric part (Lecture notes 1.15 and 1.16).

$$
\sigma_{ij} = \sigma_{ij}^{\text{sph}} + \sigma_{ij}^{\text{dev}}
$$

where $\sigma_{ij}^{\text{sph}} = \frac{1}{3} \sigma_{kk} \delta_{ij}$ is called the spherical part of the tensor. The deviatoric part is then given by

$$
\sigma_{ij}^{\text{dev}} = \sigma_{ij} - \sigma_{ij}^{\text{sph}} = \sigma_{ij} - \frac{1}{3} \sigma_{kk} \delta_{ij}
$$


In matrix notation:

$$
\boldsymbol{\sigma} =
\begin{pmatrix}
\sigma_{11} & \sigma_{12} & \sigma_{13} \\
\sigma_{21} & \sigma_{22} & \sigma_{23} \\
\sigma_{31} & \sigma_{32} & \sigma_{33}
\end{pmatrix}
$$

$$
\sigma_m = \frac{1}{3}\,\text{tr}(\boldsymbol{\sigma}) = \frac{1}{3}\left(\sigma_{11}+\sigma_{22}+\sigma_{33}\right)
$$

$$
\boldsymbol{\sigma}_{sph} = \sigma_m \, \mathbf{I} =
\begin{pmatrix}
\sigma_m & 0 & 0 \\
0 & \sigma_m & 0 \\
0 & 0 & \sigma_m
\end{pmatrix}
$$

$$
\boldsymbol{\sigma}_{dev} = \boldsymbol{\sigma} - \sigma_m \, \mathbf{I} =
\begin{pmatrix}
\sigma_{11}-\sigma_m & \sigma_{12} & \sigma_{13} \\
\sigma_{21} & \sigma_{22}-\sigma_m & \sigma_{23} \\
\sigma_{31} & \sigma_{32} & \sigma_{33}-\sigma_m
\end{pmatrix}
$$



Remark: What is the trace of a deviatoric tensor? Calculate it!

### Geometric interpretation of the strain tensor decomposition.


The following interactive illustration computes the deviatoric part and spherical part of the strain (in 2d). Starting from a square, the deformation due to the spherical and deviatoric part of the tensor are shown. Keep the values for $\epsilon_{11}, \epsilon_{12}$, and $\epsilon_{22}$ relatively low. What happens to the shape and the deformed area under deviatoric and spherical strain? Push the values for the deformation higher, does it still hold?

> The area change is due to the spherical part and the deviatoric part deforms the solid but keeps the area constant. But this only holds for infinitesimal deformation!


{{< include ../interactives/_strain_decomposition.md >}}